-- Drop the database if it already exists
DROP DATABASE IF EXISTS calorie_tracker;

-- Create a new database
CREATE DATABASE calorie_tracker;

-- Use the newly created database
USE calorie_tracker;

-- Create the Users table
CREATE TABLE Users (
  userID INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  passwordHash VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create the Foods table
CREATE TABLE Foods (
  foodID INT AUTO_INCREMENT PRIMARY KEY,
  userID INT,
  name VARCHAR(100) NOT NULL,
  calories INT NOT NULL,
  servingSize VARCHAR(50),
  dateConsumed DATE NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE
);

-- Create the Weight table
CREATE TABLE Weight (
  weightID INT AUTO_INCREMENT PRIMARY KEY,
  userID INT,
  weight DECIMAL(6, 2) NOT NULL,
  dateMeasured DATE NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE
);
